name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure compatibility with your project

      - name: Install dependencies
        run: npm install

      # Inject your secret environment variable during the build
      - name: Build the project
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

      # Deploy the build folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
